
name: Backend Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: ecommerce
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U admin -d ecommerce"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Allure CLI
        run: |
          npm install -g allure

      - name: Start FastAPI server
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: ecommerce
          DB_USER: admin
          DB_PASSWORD: admin
          BASE_URL: http://localhost:8000
        run: |
          uvicorn app:app --host 0.0.0.0 --port 8000 > server.log 2>&1 &

          for i in {1..30}; do
            if curl -s http://localhost:8000/health > /dev/null; then
              echo "FastAPI server is ready"
              exit 0
            fi

            echo "Waiting for FastAPI server..."
            sleep 2
          done

          echo "FastAPI server failed to start."
          echo "===== server.log ====="
          cat server.log
          echo "======================"
          exit 1

      - name: Run tests
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: ecommerce
          DB_USER: admin
          DB_PASSWORD: admin
          BASE_URL: http://localhost:8000
        run: |
          pytest -v

      - name: Generate Allure HTML report
        if: always()
        run: |
          allure generate reports/allure-results --output reports/allure-report

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/allure-results

      - name: Upload Allure HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports/allure-report

